# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(297, 212)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/自定义.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout_3 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox_start = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_start.setMaximum(999999999)
        self.spinBox_start.setObjectName("spinBox_start")
        self.gridLayout.addWidget(self.spinBox_start, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.spinBox_space = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_space.setMaximum(999999999)
        self.spinBox_space.setObjectName("spinBox_space")
        self.gridLayout.addWidget(self.spinBox_space, 1, 1, 1, 1)
        self.pushButton_creat = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_creat.setObjectName("pushButton_creat")
        self.gridLayout.addWidget(self.pushButton_creat, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.spinBox_num = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_num.setMaximum(999999999)
        self.spinBox_num.setObjectName("spinBox_num")
        self.gridLayout.addWidget(self.spinBox_num, 2, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.comboBox_count = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_count.setObjectName("comboBox_count")
        self.comboBox_count.addItem("")
        self.comboBox_count.addItem("")
        self.comboBox_count.addItem("")
        self.comboBox_count.addItem("")
        self.comboBox_count.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_count, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.spinBox_delay = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_delay.setMaximum(1000000300)
        self.spinBox_delay.setProperty("value", 99)
        self.spinBox_delay.setObjectName("spinBox_delay")
        self.gridLayout_2.addWidget(self.spinBox_delay, 1, 1, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout_2.addWidget(self.pushButton_send, 1, 2, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.comboBox_count.setCurrentIndex(0)
        self.pushButton_creat.clicked.connect(Dialog.creat_file)
        self.pushButton_send.clicked.connect(Dialog.send)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "自定义峰值位置"))
        self.groupBox.setTitle(_translate("Dialog", "新建峰值位置文件"))
        self.label.setText(_translate("Dialog", "起始位置："))
        self.label_2.setText(_translate("Dialog", "间隔："))
        self.pushButton_creat.setText(_translate("Dialog", "生成"))
        self.label_4.setText(_translate("Dialog", "数量："))
        self.groupBox_2.setTitle(_translate("Dialog", "发送峰值"))
        self.label_3.setText(_translate("Dialog", "通道数："))
        self.comboBox_count.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_count.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_count.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_count.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_count.setItemText(4, _translate("Dialog", "12"))
        self.label_5.setText(_translate("Dialog", "延迟时间(ms)："))
        self.pushButton_send.setText(_translate("Dialog", "发送"))
import Ui.images_rc
